---
sidebar: sidebar 
permalink: concept_asset_user_data_section.html 
summary: 通过资产页面的 User Data 部分，您可以为当前资产分配标注或应用程序。 
keywords: asset page, user data, applications, annotations 
---
= 用户数据部分
:allow-uri-read: 


[role="lead"]
资产页面的 User Data 部分将显示并允许您更改任何用户定义的数据，例如应用程序和标注。



== 使用 User Data 部分分配或修改应用程序

您可以将环境中运行的应用程序分配给某些资产（主机，虚拟机，卷，内部卷， qtree ， 和虚拟机管理程序）。通过 "User Data" 部分，您可以添加，更改或删除分配给资产的应用程序。对于除卷之外的所有这些资产类型，您可以分配多个应用程序。

.步骤
. 通过执行以下任一操作找到资产页面：
+
.. 查询资产列表，然后从列表中选择一个。
.. 在信息板上，找到资产名称并单击它。
.. 执行搜索并从结果中选择资产。
+
此时将显示资产页面。此页面的 User Data 部分将显示当前分配的应用程序或标注。





要更改分配的应用程序，或者分配应用程序或其他应用程序，请下拉 * 应用程序 * 列表并选择要分配给资产的应用程序。您可以键入以搜索应用程序，也可以从列表中选择一个应用程序。

要删除应用程序，请下拉应用程序列表并取消选中该应用程序。



== 使用 User Data 部分分配或修改标注

在自定义 Cloud Insights 以根据企业要求跟踪数据时，您可以定义称为标注的专用注释并将其分配给资产。资产页面的 "User Data" 部分显示分配给资产的标注，还可以用于更改分配给该资产的标注。

.步骤
. 要向资产添加标注，请在资产页面的 User Data 部分中单击 * + Annotation * 。
. 从列表中选择一个标注。
. 单击 Value ，然后根据您选择的标注类型执行以下操作之一：
+
.. 如果标注类型为 list ， date 或 boolean ，请从列表中选择一个值。
.. 如果标注类型为文本，请键入一个值。


. 单击保存。


标注将分配给资产。您可以稍后使用查询按标注筛选资产。

如果要在分配标注后更改其值，请下拉标注列表并输入其他值。

如果标注的列表类型选择了 _Add new values on the fly_ 选项，则除了选择现有值之外，您还可以键入以添加新值。
