---
sidebar: sidebar 
permalink: concept-write-speed.html 
keywords: write speed, high write speed, normal write speed, nvfail, writing speed, ldm, low durability mode 
summary: 您可以通过BlueXP为Cloud Volumes ONTAP 选择正常或高写入速度。在选择写入速度之前、您应该了解正常和高设置之间的差异、以及使用高速写入速度时的风险和建议。 
---
= 写入速度
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
通过BlueXP、您可以为大多数Cloud Volumes ONTAP 配置选择正常或高写入速度。在选择写入速度之前、您应该了解正常和高设置之间的差异、以及使用高速写入速度时的风险和建议。



== 正常写入速度

选择正常写入速度时，数据将直接写入磁盘。如果数据直接写入磁盘，则可以降低发生计划外系统中断或发生涉及计划外系统中断的级联故障（仅限 HA 对）时数据丢失的可能性。

默认选项为正常写入速度。



== 高写入速度

如果选择高速写入速度、则在将数据写入磁盘之前将数据缓冲在内存中、从而提供更快的写入性能。由于这种缓存，如果发生计划外系统中断，则可能会导致数据丢失。

在发生计划外系统中断时可能丢失的数据量是最后两个一致性点的范围。一致性点是将缓冲数据写入磁盘的操作。写入日志已满或 10 秒后（以先到者为准）会出现一致性点。但是，云提供商提供的存储性能可能会影响一致点处理时间。



=== 何时使用高速写入

如果您的工作负载需要快速写入性能，则写入速度是一个不错的选择，您可以承受在发生计划外系统中断或涉及计划外系统中断的级联故障（仅限 HA 对）时数据丢失的风险。



=== 使用高速写入时的建议

如果启用了高写入速度，则应确保在应用程序层提供写入保护，或者应用程序可以承受数据丢失。

ifdef::aws[]



=== 在 AWS 中使用 HA 对时写入速度较快

如果您计划在 AWS 中的 HA 对上启用高写入速度，则应了解多可用性区域（ AZ ）部署与单个 AZ 部署之间的保护级别差异。在多个 AZs 之间部署 HA 对可提供更强的故障恢复能力，并有助于降低数据丢失的可能性。

link:concept-ha.html["详细了解 AWS 中的 HA 对"]。

endif::aws[]



=== 支持高写入速度的配置

并非所有 Cloud Volumes ONTAP 配置都支持高写入速度。默认情况下，这些配置使用正常写入速度。

ifdef::aws[]



==== AWS

如果使用单节点系统，则 Cloud Volumes ONTAP 支持对所有实例类型使用高写入速度。

从 9.8 版开始，如果使用几乎所有受支持的 EC2 实例类型（ m5.xlarge 和 R5.xlarge 除外），则 Cloud Volumes ONTAP 支持 HA 对的高写入速度。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["详细了解 Cloud Volumes ONTAP 支持的 Amazon EC2 实例"^]。

endif::aws[]

ifdef::azure[]



==== Azure 酒店

如果使用单节点系统，则 Cloud Volumes ONTAP 支持对所有 VM 类型使用高写入速度。

如果使用 HA 对，则从 9.8 版开始， Cloud Volumes ONTAP 支持对多种 VM 类型使用高写入速度。转至 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["《 Cloud Volumes ONTAP 发行说明》"^] 可查看支持高写入速度的 VM 类型。

endif::azure[]

ifdef::gcp[]



==== Google Cloud

如果使用单节点系统，则 Cloud Volumes ONTAP 支持对所有计算机类型使用高写入速度。

如果使用HA对、则从9.13.0版开始、Cloud Volumes ONTAP 支持对多种VM类型使用高写入速度。转至 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html#supported-configurations-by-license["《 Cloud Volumes ONTAP 发行说明》"^] 可查看支持高写入速度的 VM 类型。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["详细了解 Cloud Volumes ONTAP 支持的 Google Cloud 计算机类型"^]。

endif::gcp[]



== 如何选择写入速度

您可以在创建新的工作环境时选择写入速度，也可以选择写入速度 link:task-modify-write-speed.html["更改现有系统的写入速度"]。



== 发生数据丢失时的预期情况

如果由于写入速度较快而导致数据丢失、事件管理系统(EMS)将报告以下两个事件：

* Cloud Volumes ONTAP 9.12.1或更高版本
+
 NOTICE nv.data.loss.possible: An unexpected shutdown occurred while in high write speed mode, which possibly caused a loss of data.
* Cloud Volumes ONTAP 9.11.0到9.11.1
+
 DEBUG nv.check.failed: NVRAM check failed with error "NVRAM disabled due to dirty shutdown with High Write Speed mode"
+
 ERROR wafl.root.content.changed: Contents of the root volume '' might have changed. Verify that all recent configuration changes are still in effect..
* Cloud Volumes ONTAP 9.8到9.10.1
+
 DEBUG nv.check.failed: NVRAM check failed with error "NVRAM disabled due to dirty shutdown"
+
 ERROR wafl.root.content.changed: Contents of the root volume '' might have changed. Verify that all recent configuration changes are still in effect.


发生这种情况时、Cloud Volumes ONTAP 应能够启动并继续提供数据、而无需用户干预。



== 如何在发生数据丢失时停止数据访问

如果您担心数据丢失，希望应用程序在数据丢失时停止运行，并希望在正确解决数据丢失问题描述后恢复数据访问，则可以使用命令行界面中的 NVFAIL 选项来实现此目标。

启用 NVFAIL 选项:: `vol modify -volume <vol-name> -nvfail on`
检查 NVFAIL 设置:: `vol show -volume <vol-name> -fields nvfail`
禁用 NVFAIL 选项:: `vol modify -volume <vol-name> -nvfail off`


发生数据丢失时，启用了 NVFAIL 的 NFS 或 iSCSI 卷应停止提供数据（不会影响无状态协议的 CIFS ）。有关详细信息，请参见 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-mgmt-dr/GUID-40D04B8A-01F7-4E87-8161-E30BD80F5B7F.html["NVFAIL 如何影响对 NFS 卷或 LUN 的访问"^]。

以检查 NVFAIL 状态:: `vol show -fields in-nvfailed-state`


正确解决数据丢失问题描述后，您可以清除 NVFAIL 状态，卷将可用于数据访问。

清除 NVFAIL 状态:: `vol modify -volume <vol-name> -in-nvfailed-state false`

