---
sidebar: sidebar 
permalink: concept-storage-management.html 
keywords: provisioning, capacity management, storage provisioning, manual, automatic, advanced allocation, aggregates, thin provisioning, free space, mode, BlueXP, cloud manager 
summary: BlueXP可简化和高级管理Cloud Volumes ONTAP 存储。 
---
= 存储管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP可简化和高级管理Cloud Volumes ONTAP 存储。


CAUTION: 必须直接从BlueXP创建和删除所有磁盘和聚合。不应从其他管理工具执行这些操作。这样做可能会影响系统稳定性、妨碍将来添加磁盘的能力、并可能产生冗余云提供商费用。



== 存储配置

通过购买磁盘和管理聚合、BlueXP可以轻松地为Cloud Volumes ONTAP 配置存储。您只需创建卷即可。如果需要，您可以使用高级分配选项自行配置聚合。



=== 简化配置

聚合可为卷提供云存储。在启动实例以及配置其他卷时、BlueXP会为您创建聚合。

创建卷时、BlueXP会执行以下三项操作之一：

* 它将卷放置在现有聚合上、该聚合具有足够的可用空间。
* 它通过为该聚合购买更多磁盘将卷放在现有聚合上。


ifdef::aws[]

+
如果AWS中的聚合支持Elelic Volumes、则BlueXP还会增加RAID组中磁盘的大小。 link:concept-aws-elastic-volumes.html["了解有关支持弹性卷的更多信息"]。

endif::aws[]

* 它为新聚合购买磁盘并将卷置于该聚合上。


BlueXP通过查看以下几个因素来确定放置新卷的位置：聚合的最大大小、是否已启用精简配置以及聚合的可用空间阈值。


TIP: 帐户管理员可以从 * 设置 * 页面修改可用空间阈值。

ifdef::aws[]



==== AWS 中聚合的磁盘大小选择

当BlueXP在AWS中为Cloud Volumes ONTAP 创建新聚合时、随着系统中聚合的数量增加、它会逐渐增加聚合中的磁盘大小。BlueXP会执行此操作、以确保您可以在系统达到AWS允许的最大数据磁盘数之前利用系统的最大容量。

例如、BlueXP可能会选择以下磁盘大小：

[cols="3*"]
|===
| 聚合编号 | Disk size | 最大聚合容量 


| 1. | 500 GiB | 3 TiB 


| 4. | 1 TiB | 6 TiB 


| 6. | 2 TiB | 12 TiB 
|===

NOTE: 此行为不适用于支持Amazon EBS弹性卷功能的聚合。启用了弹性卷的聚合由一个或两个RAID组组成。每个RAID组都有四个容量相同的相同磁盘。 link:concept-aws-elastic-volumes.html["了解有关支持弹性卷的更多信息"]。

您可以使用高级分配选项自行选择磁盘大小。

endif::aws[]



=== 高级分配

您可以自行管理聚合、而不是让BlueXP为您管理聚合。 link:task-create-aggregates.html["从 * 高级分配 * 页面"]，您可以创建包含特定数量磁盘的新聚合，向现有聚合添加磁盘以及在特定聚合中创建卷。



== 容量管理

客户管理员可以选择BlueXP是否通知您存储容量决策、或者BlueXP是否自动管理您的容量需求。

此行为由连接器上的_Capacity Management Modes_确定。容量管理模式会影响由该连接器管理的所有Cloud Volumes ONTAP 系统。如果您有另一个连接器、则可以对其进行不同的配置。



=== 自动容量管理

默认情况下，容量管理模式设置为自动。在此模式下、当需要更多容量时、BlueXP会自动为Cloud Volumes ONTAP 实例购买新磁盘、删除未使用的磁盘集合(聚合)、根据需要在聚合之间移动卷以及尝试解除磁盘故障。

以下示例说明了此模式的工作原理：

* 如果某个聚合达到容量阈值且有空间容纳更多磁盘、则BlueXP会自动为该聚合购买新磁盘、以便卷可以继续增长。
+
BlueXP每15分钟检查一次可用空间比率、以确定是否需要购买更多磁盘。



ifdef::aws[]

+
如果AWS中的聚合支持Elelic Volumes、则BlueXP还会增加RAID组中磁盘的大小。 link:concept-aws-elastic-volumes.html["了解有关支持弹性卷的更多信息"]。

endif::aws[]

* 如果聚合达到容量阈值、并且不支持任何额外磁盘、则BlueXP会自动将卷从该聚合移动到具有可用容量的聚合或新聚合。
+
如果BlueXP为卷创建新聚合、则它会选择一个可容纳该卷大小的磁盘大小。

+
请注意，可用空间现在在原始聚合上可用。现有卷或新卷可以使用该空间。在这种情况下、此空间无法返回到云提供商。

* 如果聚合中的卷数超过12小时、则BlueXP会将其删除。




==== 通过自动容量管理来管理 LUN

BlueXP的自动容量管理不适用于LUN。当BlueXP创建LUN时、它会禁用自动增长功能。



=== 手动容量管理

如果帐户管理员将容量管理模式设置为手动、则在必须决定容量时、BlueXP会显示"需要操作"消息。自动模式中描述的相同示例适用于手动模式，但您可以接受这些操作。



=== 了解更多信息。

link:task-manage-capacity-settings.html["了解如何修改容量管理模式"]。
