---
sidebar: sidebar 
permalink: concept_searching_assets.html 
summary: 高级搜索技术可以帮助您找到所需的资产。 
keywords: asset page, objects, search, advanced, alerts 
---
= 搜索资产和警报的提示和提示
:allow-uri-read: 


[role="lead"]
可以使用多种搜索方法来搜索受监控环境中的数据或对象。

* * 通配符搜索 *
+
您可以使用 * 字符执行多字符通配符搜索。例如， _applic* n_ 将返回 _application_.

* * 搜索中使用的短语 *
+
短语是一组用双引号括起来的词，例如 "VNX LUN 5" 。您可以使用双引号搜索名称或属性中包含空格的文档。

* * 布尔运算符 *
+
使用布尔运算符或，和，而不使用，您可以组合多个术语，以构成更复杂的查询。

+
或

+
OR 运算符是默认的结合运算符。

+
如果两个术语之间没有布尔运算符，则使用 OR 运算符。

+
OR 运算符链接两个术语，如果文档中存在其中任何一个术语，则会查找匹配的文档。

+
例如， _storage 或 netapp_ 会搜索包含 _storage_ 或 _netapp_ 的文档。

+
与大多数术语匹配的文档会获得高分。

+
和

+
您可以使用 AND 运算符查找一个文档中同时存在这两个搜索词的文档。例如， _storage 和 netapp_ 会搜索同时包含 _storage_ 和 _netapp_ 的文档。

+
您可以使用符号 * 和 * 代替单词和。

+
不是

+
使用 NOT 运算符时，搜索结果中将排除包含 NOT 之后的术语的所有文档。例如， _storage 而不是 netapp_ 会搜索仅包含 _storage_ 而不包含 _netapp_ 的文档。

+
您可以使用符号 * ！ * ，而不是单词 NOT 。



搜索不区分大小写。



== 使用索引词进行搜索

如果搜索与更多索引词匹配，则会获得更高的分数。

搜索字符串按空格拆分为不同的搜索词。例如，搜索字符串 "storage aurora netapp" 拆分为三个关键字： "storage" ， "aurora" 和 "netapp" 。搜索将全部使用这三个词执行。与大多数术语匹配的文档得分最高。您提供的信息越多，搜索结果越好。例如，您可以按存储名称和型号搜索存储。

用户界面会显示各个类别的搜索结果，每个类别的前三个结果。如果未找到所需的对象，则可以在搜索字符串中添加更多词以改进搜索结果。

下表列出了可添加到搜索字符串中的索引词。

|===
| 类别 | 索引术语 


| 存储 | " 存储 " 名称供应商模型 


| StoragePool | 所有关联磁盘的所有关联内部卷名称的存储存储存储供应商存储型号名称的存储 IP 地址的 "StoragePool " 名称 


| 内部卷 | 存储存储供应商存储型号存储序列号的存储 IP 地址的 " 内部卷 " 名称所有关联应用程序的所有关联共享名称的存储池名称 


| Volume | 所有内部卷的 " 卷 " 名称标签名称存储池名称存储存储存储供应商存储模型的存储序列号的存储 IP 地址的名称 


| 存储节点 | 存储存储供应商存储模型的存储序列号的存储 IP 地址的 "StorageNode" 名称 


| 主机 | 所有关联应用程序的 "host" 名称 IP 地址名称 


| 数据存储库 | "datastore" 名称所有内部卷的所有卷的虚拟中心 IP 名称 


| 虚拟机 | "VirtualMachine" 名称 DNS 名称 IP 地址所有关联应用程序的所有数据存储库名称的主机 IP 地址的名称 


| 交换机（常规和 NPV ） | "switch" IP 地址 WWN 名称序列号型号网络结构 WWN 的域 ID 名称 


| 应用程序 | " 应用程序 " 名称租户业务部门业务单位项目 


| 磁带 | "tape" IP 地址名称序列号供应商 


| Port | " 端口 "WWN 名称 


| 网络结构 | " 网络结构 "WWN 名称 


| Storage Virtual Machine （ SVM ） | "storagevirtualmachine" 名称 UUID 
|===