---
sidebar: sidebar 
permalink: concept_forensic.html 
keywords: Forensic, user, entity, community 
summary: 取证概述 
---
= 取证信息
:toc: macro
:hardbreaks:
:toclevels: 1
:history: Review 1/17,
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
通过取证视图，您可以访问用户，实体，社区和用户活动信息。



== 检查用户信息

单击 * 取证 > 用户 * 以访问用户视图。

此视图显示常规用户信息：

* 用户的名称，其中包含指向用户详细信息的链接。
* 用户活动引发的警报
* 用户所属社区的数量，其中包含指向 "communites" 页面的链接
* 用户的位置
* 用户访问的最后一个实体


单击用户名可在中访问更多详细信息 link:forensic_user_detail.html["用户概述"]



== 检查实体信息

单击 * 取证 > 实体 * 以访问实体视图。

此页面显示了用户正在访问的实体的常规信息：

介绍详细信息，包括：

* 实体名称
* 实体类型


* 与实体的社区关系
* 实体路径
* 上次访问时间
* 实体大小


单击实体名称可在中访问更多详细信息 link:forensic_entity_detail.html["实体概述"]

单击 Community count 以显示包含此实体的社区。



== 检查社区信息

单击 * 取证 > 社区 * 以访问社区页面。

此视图可提供：

* 社区名称
* 与社区相关的警报
* 社区的用户计数
* 实体计入社区


单击或搜索社区名称以访问社区详细信息页面。

社区概况:: 列出社区用户位置以及其他最接近的社区。
社区行为:: 显示访问的实体数量，并显示读取，写入和元数据访问操作。
用户和实体:: 标识社区中的用户总数和实体总数。
社区分析::
+
--
* 社区用户趋势
* 对实体执行的操作
* 警报趋势


--


单击社区名称可在中访问更多详细信息 link:forensic_community_detail.html["社区详细信息"]



== 检查用户活动信息

单击 * 取证 > 用户活动 * 以访问用户活动视图。

对于要监控的每个用户，此视图介绍：

* 实体访问时间
* 通过用户概述链接访问实体的用户
* 执行的活动：
+
** 读取
** 写入
** 创建
** 重命名


* 实体路径
* 实体类型
* 访问位置单击用户名可在中访问更多详细信息 link:forensic_user_detail.html["实体详细信息"]

