---
sidebar: sidebar 
permalink: concept-worm.html 
keywords: worm, write once, read many, snaplock, retain, retention, period, cloud worm, worm storage, tiering 
summary: 您可以在 Cloud Volumes ONTAP 系统上激活一次写入、多次读取（ WORM ）存储、以在指定的保留期内以未经修改的形式保留文件。云 WORM 存储由 SnapLock 技术提供支持，这意味着 WORM 文件在文件级别受到保护。 
---
= WORM 存储
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在 Cloud Volumes ONTAP 系统上激活一次写入、多次读取（ WORM ）存储、以在指定的保留期内以未经修改的形式保留文件。云 WORM 存储由 SnapLock 技术提供支持，这意味着 WORM 文件在文件级别受到保护。



== WORM 存储的工作原理

将文件提交到 WORM 存储后，即使在保留期限到期后，也无法对其进行修改。防篡改时钟将确定 WORM 文件的保留期已过。

保留期结束后、您将负责删除不再需要的任何文件。



== 正在充电

根据 WORM 卷的总配置容量， WORM 存储的费用为每小时一次。

WORM许可仅适用于PAYGO或年度承诺条款、可通过云提供商的市场购买。WORm既支持基于节点的许可模式、也支持基于容量的许可模式。


NOTE: BYOL许可不适用于Cloud Volumes ONTAP上的WORM存储。

您应了解Cloud Volumes ONTAP 9.10.1及更高版本的以下充电行为：

* 从ONTAP 9.10.1开始、WORM卷和非WORM卷可以位于同一聚合上。
* 如果在创建Cloud Volumes ONTAP 工作环境时启用了WORM、则从BlueXP创建的每个卷都会启用WORM。但是、您可以使用ONTAP 命令行界面或系统管理器创建已禁用WORM的卷。这些卷不按WORM速率充电。
* 如果在创建工作环境时未启用WORM、则从BlueXP创建的每个卷都会禁用WORM。这些卷不按WORM速率计费。


https://cloud.netapp.com/pricing["了解 WORM 存储的定价"^]



== 激活 WORM 存储

激活WORM存储的方式取决于所使用的Cloud Volumes ONTAP 版本。



=== 9.10.1及更高版本

从Cloud Volumes ONTAP 9.10.1开始、您可以选择在卷级别启用或禁用WORM。

创建新的Cloud Volumes ONTAP 工作环境时、系统会提示您启用或禁用WORM存储：

* 如果在创建工作环境时启用了WORM存储、则从BlueXP创建的每个卷都会启用WORM。但是、您可以使用System Manager或CLI创建已禁用WORM的卷。
* 如果在创建工作环境时禁用WORM存储、则从BlueXP、System Manager或CLI创建的每个卷都会禁用WORM。如果要在创建期间未启用的Cloud Volumes ONTAP 工作环境中启用WORM、则必须向NetApp支持部门创建一个支持服务单以获得帮助。


无论选择哪种方案、您都应选择此选项 <<正在充电,了解充电的工作原理>>。



=== 9.10.0及更早版本

您可以在创建新的工作环境时在 Cloud Volumes ONTAP 系统上激活 WORM 存储。从BlueXP创建的每个卷都已启用WORM。您不能在单个卷上禁用WORM存储。



== 将文件提交到 WORM

您可以使用应用程序通过 NFS 或 CIFS 将文件提交到 WORM ，或者使用 ONTAP CLI 自动将文件提交到 WORM 。您还可以使用 WORM 附加文件来保留增量写入的数据，例如日志信息。

在 Cloud Volumes ONTAP 系统上激活 WORM 存储后，必须使用 ONTAP CLI 对 WORM 存储进行所有管理。有关说明，请参见 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-arch-con/home.html["ONTAP 文档"^]。



== 正在删除WORM文件

您可以使用特权删除功能在保留期间删除WORM文件。

有关说明，请参见 https://docs.netapp.com/us-en/ontap/snaplock/delete-worm-files-concept.html["ONTAP 文档"^]



== WORM和数据分层

创建新的Cloud Volumes ONTAP 9.8或更高版本系统时、您可以同时启用数据分层和WORM存储。通过使用WORM存储启用数据分层、您可以将数据分层到云中的对象存储。

您应了解以下有关启用数据分层和WORM存储的信息：

* 分层到对象存储的数据不包括ONTAP WORM功能。要确保端到端WORM功能、您需要正确设置存储分段权限。
* 分层到对象存储的数据不具有WORM功能、这意味着从技术上讲、对存储分段和容器具有完全访问权限的任何人都可以转到并删除ONTAP 分层的对象。
* 启用WORM和分层后、将阻止还原或降级到Cloud Volumes ONTAP 9.8。




== 限制

* Cloud Volumes ONTAP 中的 WORM 存储在 " 可信存储管理员 " 模式下运行。虽然 WORM 文件不受更改或修改的影响，但集群管理员可以删除卷，即使这些卷包含未过期的 WORM 数据也是如此。
* 除了可信存储管理员模式之外， Cloud Volumes ONTAP 中的 WORM 存储还隐式地在 " 可信云管理员 " 模式下运行。云管理员可以通过直接从云提供商中删除或编辑云存储，在 WORM 数据到期之前将其删除。

