---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, flexgroup, ontap s3, s3 configuration, svm dr, svm disaster recovery, disaster recovery, storage vm dr, BlueXP, cloud manager 
summary: 已知限制确定了本产品版本不支持的平台、设备或功能、或者这些平台、设备或功能无法与产品正确交互操作。仔细审查这些限制。 
---
= 已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制确定了本产品版本不支持的平台、设备或功能、或者这些平台、设备或功能无法与产品正确交互操作。仔细审查这些限制。

这些限制特定于BlueXP中的Cloud Volumes ONTAP 管理。要查看 Cloud Volumes ONTAP 软件本身的限制， https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limitations.html["转至《 Cloud Volumes ONTAP 发行说明》"^]



== BlueXP不支持创建FlexGroup 卷

虽然Cloud Volumes ONTAP 支持FlexGroup 卷、但BlueXP目前不支持FlexGroup 卷创建。如果您从System Manager或CLI创建FlexGroup 卷、则应将BlueXP的容量管理模式设置为手动。对于 FlexGroup 卷，自动模式可能无法正常工作。


NOTE: 计划在未来版本中创建FlexGroup 卷。



== 在Cloud Volumes ONTAP 中、BlueXP不支持S3

虽然Cloud Volumes ONTAP支持将S3作为横向扩展存储的一个选项、但BlueXP不会为此功能提供任何管理功能。最好使用命令行界面从 Cloud Volumes ONTAP 配置 S3 客户端访问。有关详细信息，请参见 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html["《 S3 配置高级指南》"^]。

link:concept-client-protocols.html["详细了解Cloud Volumes ONTAP 对S3和其他客户端协议的支持"]。



== BlueXP不支持对Storage VM进行灾难恢复

BlueXP不为Storage VM (SVM)灾难恢复提供任何设置或流程编排支持。您必须使用 System Manager 或 CLI 。

link:task-manage-svm-dr.html["详细了解SVM灾难恢复"]。



== 测试AsciDoc字符替换和内在属性

通过所有语言的本地化和发布进行端到端测试。

.星号
｛Asterisk｝
文本｛Asterisk｝
文本｛Asterisk｝
文本｛Asterisk｝文本

.双冒号
｛two-colons｝
文本｛two-colons｝
文本｛two-colons｝
文本｛two-colons｝文本

.垂直条
｛vbar｝
文本｛vbar｝
文本｛vbar｝
文本｛vbar｝文本

.以及
｛plus｝
文本｛plus｝
文本｛plus｝
文本｛plus｝文本

.方括号
｛Startsb｝和｛endsb｝
文本｛Startsb｝和文本｛endsb｝
文本｛Startsb｝和文本｛endsb｝
文本｛Startsb｝和文本｛endsb｝文本

.不间断空格
在｛｛｝之后

.零宽度空间
在｛zwsp｝之前
