---
sidebar: sidebar 
permalink: reporting_user_roles.html 
summary: 您可以使用 Cloud Insights 报告执行哪些操作取决于您的用户角色。 
keywords: reporting, cognos, data warehouse, dwh, users, roles, user roles 
---
= Cloud Insights 报告用户角色


[role="lead"]
如果您拥有具有报告功能的 Cloud Insights 高级版，则环境中的每个 Cloud Insights 用户还可以通过单点登录（ Single Sign-On ， SSO ）登录到报告应用程序（即 Cognos ）。只需单击菜单中的 * 报告 * 链接，您就会自动登录到报告。

您在 Cloud Insights 中的用户角色决定了您的报告用户角色：

|===


| Cloud Insights 角色 | 报告角色 | 报告权限 


| 来宾 | 使用者 | 可以查看，计划和运行报告并设置个人首选项，例如语言和时区的首选项。使用者不能创建报告或执行管理任务。 


| 用户 | 作者 | 可以执行所有使用者功能以及创建和管理报告和信息板。 


| 管理员 | 管理员 | 可以执行所有作者功能以及所有管理任务，例如配置报告以及关闭和重新启动报告任务。 
|===
下表显示了每个报告角色可用的功能。

|===


| 功能 | 使用者 | 作者 | 管理员 


| 在 " 团队内容 " 选项卡中查看报告 | 是的。 | 是的。 | 是的。 


| 运行报告 | 是的。 | 是的。 | 是的。 


| 计划报告 | 是的。 | 是的。 | 是的。 


| 上传外部文件 | 否 | 是的。 | 是的。 


| 创建作业 | 否 | 是的。 | 是的。 


| 创建案例 | 否 | 是的。 | 是的。 


| 创建报告 | 否 | 是的。 | 是的。 


| 创建软件包和数据模块 | 否 | 是的。 | 是的。 


| 执行管理任务 | 否 | 否 | 是的。 
|===


== 设置报告（ Cognos ）电子邮件首选项


NOTE: 如果您在 Cloud Insights 报告中更改了用户电子邮件首选项（例如 Cognos 应用程序），则这些首选项对于当前会话为 active _only 。注销 Cognos 并重新登录将重置您的电子邮件首选项。



== 现有客户的重要注意事项

如果您是首次使用 Cloud Insights 报告功能的用户，欢迎使用！您无需再做任何其他事情即可开始享受报告。

如果您是最新的 Premium Edition 客户，则不会自动为您的环境启用 SSO 。启用 SSO 后，报告门户（ Cognos ）的管理员用户将停止存在。这意味着， _My Content_ 文件夹中的任何报告都将被删除，必须在 _Team Content_ 中重新安装或重新创建。此外，启用 SSO 后，需要配置计划的报告。



=== 我应采取哪些步骤来准备现有环境以启用 SSO ？

要确保您的报告得以保留，请使用以下步骤将所有报告从 _My Content_ 迁移到 _Team Content_ 。在您的环境中启用 SSO 之前，您必须先执行此操作：

. 在 _Team Content_ 中创建新文件夹
+
.. 如果已创建多个用户，请为每个用户创建一个单独的文件夹，以避免覆盖名称重复的报告


. 导航到 _My Content_
. 选择要保留的所有报告。
. 在菜单右上角，选择 " 复制或移动 "
. 导航到 _Team Content_ 中新创建的文件夹
. 使用 " 复制到 " 或 " 移动到 " 按钮将报告粘贴到新创建的文件夹中
. 为 Cognos 启用 SSO 后，使用用于创建帐户的电子邮件地址登录到 Cloud Insights 。
. 导航到 Cognos 中的 _Team Content_ 文件夹，然后将先前保存的报告复制或移动回 _My Content_ 。

