---
sidebar: sidebar 
permalink: task_dc_hds_nas.html 
keywords: data collector, HDS HNAS, HDS NAS 
summary: 配置 HDS NAS （ HNAS ）数据收集器。 
---
= 配置 Hitachi Vantara NAS 数据收集器


[role="lead"]
Hitachi Vantara NAS 数据收集器是一个清单和配置数据收集器，支持发现 HDS NAS 集群。Cloud Insights 支持发现 NFS 和 CIFS 共享，文件系统（内部卷）和跨区（存储池）。



== 术语

Cloud Insights 从 HNAS 数据收集器采集以下清单信息。对于 Cloud Insights 收购的每种资产类型，均显示了此资产最常用的术语。查看此数据收集器或对其进行故障排除时，请记住以下术语：

[cols="2*"]
|===
| 供应商 / 型号术语 | Cloud Insights 术语 


| 层 | 磁盘组 


| 集群 | 存储 


| Node | 存储节点 


| 范围 | 存储池 


| 系统驱动器 | 后端 LUN 


| 文件系统 | 内部卷 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情形。



== 要求

* 设备 IP 地址
* 端口 22 ， SSH 协议
* username and password —权限级别： supervisor
* 注意：此数据收集器基于 SSH ，因此托管此数据收集器的 AU 必须能够在 HNAS 本身或集群所连接的系统管理单元（ SMU ）上启动与 TCP 22 的 SSH 会话。




== Configuration

[cols="2*"]
|===
| 字段 | Description 


| HNAS 主机 | HNAS 管理主机的 IP 地址或完全限定域名 


| 用户名 | HNAS CLI 的用户名 


| Password | HNAS CLI 使用的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | Description 


| 清单轮询间隔（分钟） | 两次清单轮询的间隔。默认值为 30 分钟。 
|===


== 故障排除

如果此数据收集器出现问题，请尝试执行以下操作：



==== 清单

[cols="2*"]
|===
| 问题： | 请尝试以下操作： 


| 连接时出错，并显示错误消息 " 设置 Shell 通道时出错： " 或 " 打开 Shell 通道时出错 " | 可能是由于网络连接问题或 SSH 配置不当而导致的。确认与备用 SSH 客户端的连接 


| 超时或检索数据时出错，并显示错误消息 "Command ： xxx has timed out" 。 | * 尝试使用备用 SSH 客户端执行命令 * 增加超时 


| 连接 " 或 " 登录凭据无效 " 时出错，并显示错误消息 " 无法与设备通信： " | * 检查 IP 地址 * 检查用户名和密码 * 确认与备用 SSH 客户端的连接 
|===
可以从找到追加信息 link:concept_requesting_support.html["支持"] 页面或中的 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["数据收集器支持列表"]。
