---
sidebar: sidebar 
permalink: task_config_cs_data_collectors.html 
keywords: acquisition, AU, data collector, collector 
summary: 配置数据收集器 
---
= 配置数据收集器
:allow-uri-read: 


[role="lead"]
您可以在 Cloud Insights 环境中配置数据收集器，以便从数据中心中的主机，服务或设备收集数据。

.开始之前
* 要配置数据收集器，您必须具有帐户所有者或管理员权限。
* 您必须先配置采集单元（用于基础架构）或代理（用于服务或主机），然后才能开始收集数据。
* 您需要用于收集数据的基础架构设备的凭据。
+
要从中收集数据的所有设备都需要设备网络地址，帐户信息和密码。





=== 凭据安全性

在 Cloud Insights 中输入数据收集器凭据时，这些凭据会进行加密，并首先通过 AU 的公有密钥加密并通过 HTTPS 加密发送到采集单元（ AU ）。当 AU 使用加密值与设备和软件进行通信时，加密值会进行解密。



=== 配置 Data Collector

* 从 Cloud Insights 菜单中，单击 * 管理 > 数据收集器 * ，然后单击 * + 数据收集器 * 按钮。您可以选择显示所有数据收集器，也可以选择筛选以仅显示根据您的订阅可供您使用的数据收集器。


* 根据您选择的数据收集器类型，安装步骤会有所不同。




==== 操作系统：

要开始从环境中收集操作系统或服务数据，必须至少安装一个 Cloud Insights 代理。您可以根据需要安装任意数量的代理。每个代理都可以从多个服务收集数据。

除了从服务收集数据之外，每个代理还充当安装它的 VM/ 主机的数据收集器。收集的数据在信息板小工具或查询中显示为 " 节点 " 数据。

. 单击要从中访问 Cloud Insights 的 VM 或主机（即节点）的平台类型或操作系统。
. 选择代理访问密钥。
. 将显示的命令复制到剪贴板。您可以单击剪贴板图标以快速复制命令。
. 在代理 VM/ 主机上打开终端 / 命令窗口，然后粘贴命令。按 Enter 执行命令。
. 安装代理后，单击 * 完成 * 。代理将开始收集数据。
+
在信息板中显示节点数据或可供查询之前，可能需要长达两个轮询周期。





==== 服务

服务数据收集器是指基于电报代理的服务数据收集器，例如 Docker 或 Kibana 。

.开始之前
* 您必须至少有一个 Cloud Insights 代理才能从您的环境中收集服务数据。如果您未安装代理，则在配置服务数据收集器时，系统将提示您安装一个代理。
* 必须在您的环境中安装并运行要从中收集数据的服务。
+
.. 单击服务数据收集器。
.. 选择代理操作系统或平台。如果尚未为平台安装代理，请按照说明进行操作。
.. 选择代理访问密钥。
.. 单击 * 继续 * 。
.. 按照说明配置数据收集器。您可以单击剪贴板图标以快速复制显示的命令或代码片段。
.. 正确配置数据收集器后，单击 * 完成 * 。
+
可能需要长达两个轮询周期，才能将服务中的数据显示在信息板中或用于查询。







==== 基础架构：

基础架构数据收集器包括存储或交换机等内容。

.开始之前
* 您必须至少配置一个采集单元，才能开始收集基础架构数据。
+
.. 单击基础架构数据收集器。
.. 输入数据收集器的名称。名称可以包含以下字符：


* 字母（ a-z ）
* 数量（ 0-9 ）
* 连字符（ - ）
* 下划线（ _ ）
* 句点（ . ）
* 空间（）
+
名称不能以空格，句点或连字符开头或结尾。

+
.. 输入要与此数据收集器关联的采集单元。
.. 在配置屏幕中输入所需字段。
.. 单击 * 高级配置 * 以输入其他配置字段。并非所有数据收集器都需要高级配置。
.. 单击 * 测试配置 * 以验证是否已正确配置数据收集器。
.. 完成后，单击 * 添加收集器 * 。




有关添加新采集单元的帮助，请参见 link:task_configure_acquisition_unit.html["配置采集单元"]

+ 可能需要长达两个轮询周期，才能将来自环境的数据显示在信息板中或用于查询。
