---
sidebar: sidebar 
permalink: task_create_annotation_rules.html 
summary: 您可以创建标注规则以自动将标注应用于多个资产。 
---
= 正在创建标注规则
:allow-uri-read: 


[role="lead"]
您可以使用标注规则根据定义的条件自动将标注应用于多个资产。Cloud Insights 会根据这些规则为资产分配标注。在 Cloud Insight 评估标注规则时，在单个资产页面上手动设置的标注优先于基于规则的标注。

您必须已为标注规则创建查询。

.步骤
. 在 Cloud Insights 菜单中，单击 * 管理 > 标注规则 * 。
. 单击 * + Rule* 以添加新的标注规则。
+
此时将显示添加规则对话框。

. 执行以下操作：
+
.. 在 * 名称 * 框中，输入用于描述规则的唯一名称。
+
此名称将显示在 "Annotation Rules" 页面中。

.. 单击 * 查询 * ，然后选择 Cloud Insights 用于标识标注适用场景的资产的查询。
.. 单击 * 标注 * 并选择要应用的标注。
.. 单击 * 值 * 并为标注选择一个值。
+
例如，如果选择 " 生日 " 作为标注，则可以为此值指定日期。

.. 单击 * 保存 * 。
.. 如果要立即运行所有规则，请单击 * 运行所有规则 * ；否则，这些规则将按计划的定期间隔运行。
+

NOTE: 在大型 Cloud Insights 环境中，您可能会发现运行标注规则似乎需要一段时间才能完成。这是因为索引器首先运行，并且必须在运行规则之前完成。通过索引器， Cloud Insights 可以搜索或筛选数据中的新对象和计数器或更新的对象和计数器。规则引擎会等待索引器完成更新，然后再应用规则。







== 修改标注规则

您可以修改标注规则以更改规则的名称，标注，标注值或与规则关联的查询。

.步骤
. 在 Cloud Insights 菜单中，单击 * 管理 > 标注规则 * 。
+
" 标注规则 " 页面将显示现有标注规则的列表。

. 找到要修改的标注规则。
+
您可以通过在筛选器框中输入值来筛选标注规则，也可以单击页码按页浏览标注规则。

. 单击要修改的规则对应的菜单图标。
. 单击 * 编辑 * 。
+
此时将显示编辑规则对话框。

. 修改标注规则的名称，标注，值或查询。




== 更改规则顺序

标注规则会从规则列表顶部到底部进行处理。要更改规则的处理顺序，请执行以下操作：

.步骤
. 单击要移动的规则对应的菜单图标。
. 根据需要单击 * 上移 * 或 * 下移 * ，直到规则显示在所需位置。




== 正在删除标注规则

您可能希望删除不再使用的标注规则。

.步骤
. 在 Cloud Insights 菜单中，单击 * 管理 > 标注规则 * 。
+
" 标注规则 " 页面将显示现有标注规则的列表。

. 找到要删除的标注规则。
+
您可以通过在筛选器框中输入值来筛选标注规则，也可以单击页码按页浏览标注规则。

. 单击要删除的规则对应的菜单图标。
. 单击 * 删除 * 。
+
此时将显示一条确认消息，提示您是否要删除此规则。

. 单击 * 确定 * 。

