---
sidebar: sidebar 
permalink: task-verify-autosupport.html 
keywords: autosupport, set up autosupport, test autosupport, asup, test asup 
summary: AutoSupport 会主动监控系统的运行状况，并向 NetApp 技术支持发送消息。默认情况下，每个节点都启用了 AutoSupport ，以便使用 HTTPS 传输协议向技术支持发送消息。最好验证 AutoSupport 是否可以发送这些消息。 
---
= 验证 AutoSupport 设置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AutoSupport 会主动监控系统的运行状况，并向 NetApp 技术支持发送消息。默认情况下，每个节点都启用了 AutoSupport ，以便使用 HTTPS 传输协议向技术支持发送消息。最好验证 AutoSupport 是否可以发送这些消息。

唯一需要的配置步骤是确保 Cloud Volumes ONTAP 具有出站 Internet 连接。有关详细信息，请参阅云提供商的网络要求。



== AutoSupport 要求

Cloud Volumes ONTAP 节点需要通过出站Internet访问NetApp AutoSupport 、NetApp会主动监控系统运行状况并向NetApp技术支持发送消息。

路由和防火墙策略必须允许通过 HTTP/HTTPS 流量访问以下端点，以便 Cloud Volumes ONTAP 可以发送 AutoSupport 消息：

* \https://support.netapp.com/aods/asupmessage
* \https://support.netapp.com/asupprod/post/1.0/postAsup


如果无法通过出站Internet连接发送AutoSupport 消息、则BlueXP会自动将您的Cloud Volumes ONTAP 系统配置为使用Connector作为代理服务器。唯一的要求是确保Connector的安全组允许通过端口3128进行_inbound_连接。部署Connector后、您需要打开此端口。

如果您为Cloud Volumes ONTAP 定义了严格的出站规则、则还需要确保Cloud Volumes ONTAP 安全组允许通过端口3128进行_outout_连接。

确认出站 Internet 访问可用后，您可以测试 AutoSupport 以确保它可以发送消息。有关说明，请参见 https://docs.netapp.com/us-en/ontap/system-admin/setup-autosupport-task.html["ONTAP 文档：设置 AutoSupport"^]。



== 对AutoSupport 配置进行故障排除

如果出站连接不可用、并且BlueXP无法将您的Cloud Volumes ONTAP 系统配置为使用此连接器作为代理服务器、您将从BlueXP收到一条通知、标题为"<工作环境名称>无法发送AutoSupport 消息"。

您很可能会因为网络问题而收到此消息。

请按照以下步骤解决此问题。

.步骤
. 通过SSH连接到Cloud Volumes ONTAP 系统、以便您可以从命令行界面管理系统。
+
link:task-connecting-to-otc.html["了解如何通过SSH连接到Cloud Volumes ONTAP"]。

. 显示 AutoSupport 子系统的详细状态：
+
`autosupport check show-details`

+
响应应类似于以下内容：

+
[listing]
----
    Category: smtp
          Component: mail-server
             Status: failed
             Detail: SMTP connectivity check failed for destination:
                     mailhost. Error: Could not resolve host - 'mailhost'
            Corrective Action: Check the hostname of the SMTP server

    Category: http-https
        Component: http-put-destination
            Status: ok
            Detail: Successfully connected to:
                    <https://support.netapp.com/put/AsupPut/>.

          Component: http-post-destination
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/asupprod/post/1.0/postAsup.

    Category: on-demand
          Component: ondemand-server
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/aods/asupmessage.

    Category: configuration
            Component: configuration
                Status: ok
                Detail: No configuration issues found.
    5 entries were displayed.
----
+
如果http-https类别的状态为"ok"、则表示已正确配置AutoSupport 、可以发送消息。

. 如果状态不正确、请验证每个Cloud Volumes ONTAP 节点的代理URL：
+
`autosupport show -fields proxy-url`

. 如果proxy URL参数为空、请将Cloud Volumes ONTAP 配置为使用Connector作为代理：
+
`autosupport modify -proxy-url \http://<connector private ip>:3128`

. 再次验证AutoSupport 状态：
+
`autosupport check show-details`

. 如果状态仍为FAILED、请验证Cloud Volumes ONTAP 与连接器之间是否通过端口3128建立连接。
. 如果在验证是否存在连接后状态ID仍然失败、请通过SSH连接到连接器。
+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-managing-connectors.html#connect-to-the-linux-vm["了解有关连接到Linux VM for the Connector的更多信息"^]

. 转至 `/opt/application/netapp/cloudmanager/docker_occm/data/`
. 打开代理配置文件 `squid.conf`
+
文件的基本结构如下：

+
[listing]
----
        http_port 3128
        acl localnet src 172.31.0.0/16
        acl azure_aws_metadata dst 169.254.169.254

        http_access allow localnet
        http_access deny azure_aws_metadata
        http_access allow localhost
        http_access deny all
----
+
localnet src值是Cloud Volumes ONTAP 系统的CIDR。

. 如果Cloud Volumes ONTAP 系统的CIDR块不在文件中指定的范围内、请按如下所示更新此值或添加新条目：
+
`acl cvonet src <cidr>`

+
如果添加此新条目、请勿忘记同时添加一个允许条目：

+
`http_access allow cvonet`

+
以下是一个示例：

+
[listing]
----
        http_port 3128
        acl localnet src 172.31.0.0/16
        acl cvonet src 172.33.0.0/16
        acl azure_aws_metadata dst 169.254.169.254

        http_access allow localnet
        http_access allow cvonet
        http_access deny azure_aws_metadata
        http_access allow localhost
        http_access deny all
----
. 编辑此配置文件后、以sudo身份重新启动代理容器：
+
`docker restart squid`

. 返回到Cloud Volumes ONTAP 命令行界面并验证Cloud Volumes ONTAP 是否可以发送AutoSupport 消息：
+
`autosupport check show-details`


