---
sidebar: sidebar 
permalink: task_device_resolution_rules.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution 
summary: 设备解析有助于您准确跟踪环境中的性能和清单。 
---
= 设备解析规则


[role="lead"]
您可以创建设备解析规则来标识 Cloud Insights 当前未自动标识的主机，存储和磁带。您创建的规则用于标识当前环境中的设备，并在将类似设备添加到环境中时标识这些设备。



== 正在创建设备解析规则

创建规则时，首先要确定规则所针对的信息源，用于提取信息的方法以及是否对规则结果应用 DNS 查找。

[cols="2*"]
|===


| 用于标识设备的源 | * 主机的 SRM 别名 * 包含嵌入式主机或磁带名称的存储别名 * 包含嵌入式主机或磁带名称的交换机别名 * 包含嵌入式主机名的分区名称 


| 用于从源提取设备名称的方法 | * 原样（从 SRM 提取名称） * 分隔符 * 正则表达式 


| DNS 查找 | 指定是否使用 DNS 验证主机名 
|===
您可以在自动解析规则选项卡中创建规则。以下步骤介绍了规则创建过程。

.操作步骤
. 单击 * 管理 > 设备解析 *
. 在 * 自动解析规则 * 选项卡中，单击 * + 主机规则 * 或 * + 磁带规则 * 。
+
此时将显示 * 解析规则 * 屏幕。

+

NOTE: 单击 _view matching Criteria_ 链接，获取有关创建正则表达式的帮助和示例。

. 在 * 类型 * 列表中，选择要标识的设备。
+
您可以选择 _Host_ 或 _Tape 。

. 在 * 源 * 列表中，选择要用于标识主机的源。
+
根据您选择的源， Cloud Insights 将显示以下响应：

+
.. * 分区 * 列出了需要通过 Cloud Insights 标识的分区和 WWN 。
.. * SRM * 列出了需要由 Cloud Insights 标识的未标识别名
.. * 存储别名 * 列出了需要由 Cloud Insights 标识的存储别名和 WWN
.. * 交换机别名 * 列出了需要由 Cloud Insights 标识的交换机别名


. 在 * 方法 * 列表中，选择要用于标识主机的方法。
+
|===


| 源 | 方法 


| SRM | 分隔符，正则表达式也是一样 


| 存储别名 | 分隔符，正则表达式 


| 交换机别名 | 分隔符，正则表达式 


| 分区 | 分隔符，正则表达式 
|===
+
** 使用分隔符的规则需要使用分隔符和主机名的最小长度。主机名的最小长度是 Cloud Insights 标识主机时应使用的字符数。Cloud Insights 仅对长度超过此长度的主机名执行 DNS 查找。
+
对于使用分隔符的规则，输入字符串由分隔符标记，并通过对相邻令牌进行多种组合来创建主机名候选对象列表。然后，该列表将按从大到小的顺序进行排序。例如，对于 _vipsnq03_hba3_emc3_12ep0_ 的输入 sring ，此列表将导致以下结果：

+
*** vpsnq03_hba3_emc3_12ep0
*** vpsnq03_hba3_emc3
*** hba3 emc3_12ep0
*** vpsnq03_hba3
*** emc3_12ep0
*** hba3_emc3.
*** vpsnq03
*** 12ep0
*** emc3.
*** hba3.


** 使用正则表达式的规则需要选择正则表达式，格式和区分大小写。


. 单击 * 运行 AR* 以运行所有规则，或者单击按钮中的向下箭头以运行您创建的规则（以及自上次完全运行 AR 以来创建的任何其他规则）。
+
规则运行的结果显示在 * FC Identify" 选项卡中。





== 启动自动设备解析更新

设备解析更新会提交自上次运行完全自动设备解析以来添加的手动更改。运行更新只能用于提交和运行对设备解析配置所做的新手动条目。不执行完整的设备解析运行。

.操作步骤
. 登录到 Cloud Insights Web UI 。
. 单击 * 管理 > 设备解析 *
. 在 * 设备解析 * 屏幕中，单击 * 运行 AR* 按钮中的向下箭头。
. 单击 * 更新 * 开始更新。




== 规则辅助手动标识

如果您希望运行特定规则或规则列表（无论是否一次性重新排序）来解析未知主机，存储和磁带设备，则可以使用此功能。

您有许多设备尚未标识，您也有多个规则可以成功标识其他设备。


NOTE: 如果源仅包含主机或设备名称的一部分，请使用正则表达式规则并对其进行格式化以添加缺少的文本。

.操作步骤
. 登录到 Cloud Insights Web UI 。
. 单击 * 管理 > 设备解析 *
. 单击 * 光纤通道标识 * 选项卡。
+
系统将显示这些设备及其解析状态。

. 选择多个未标识的设备。
. 单击 * 批量操作 * 并选择 * 设置主机解析 * 或 * 设置磁带解析 * 。
+
系统将显示 "Identify" 屏幕，其中包含成功标识设备的所有规则的列表。

. 将规则的顺序更改为满足您需求的顺序。
+
规则的顺序会在 "Identify" 屏幕中更改，但不会全局更改。

. 选择满足您需求的方法。


Cloud Insights 按照方法的显示顺序执行主机解析过程，从顶部的顺序开始。

遇到应用的规则时，规则名称将显示在规则列中，并标识为手动。

相关：link:task_device_resolution_fibre_channel.html["光纤通道设备解析"]


