---
sidebar: sidebar 
permalink: task_dc_na_eseries.html 
keywords: data collector, ontap, clustered ontap 
summary: 配置 NetApp E 系列数据收集器。 
---
= NetApp E 系列数据收集器


[role="lead"]
NetApp E 系列数据收集器可收集清单和性能数据。此收集器支持使用相同配置并报告相同数据的固件 7.x+ 。



== 术语

Cloud Insight 从 NetApp E 系列数据收集器采集以下清单信息。对于所采集的每种资产类型，均显示了此资产最常用的术语。查看此数据收集器或对其进行故障排除时，请记住以下术语：

[cols="2*"]
|===
| 供应商 / 型号术语 | Cloud Insights 术语 


| Disk | Disk 


| 卷组 | 磁盘组 


| 存储阵列 | 存储 


| 控制器 | 存储节点 


| 卷组 | 存储池 


| Volume | Volume 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情形。



== E 系列术语（登录页面）

以下术语适用于您在 NetApp E 系列资产登录页面上可能找到的对象或参考。其中许多术语也适用于其他数据收集器。



=== 存储

* Model —设备的型号名称。
* vendor —与配置新数据源时看到的供应商名称相同
* Serial Number —阵列序列号。在 NetApp 集群模式 Data ONTAP 等集群架构存储系统上，此序列号可能不如单个 " 存储节点 " 序列号有用
* IP —通常是数据源中配置的 IP 或主机名
* 微代码版本—固件
* 原始容量—系统中所有物理磁盘的基本 2 总和，而不管其角色如何
* 延迟—表示主机在读取和写入工作负载方面所遇到的情况。理想情况下， Cloud Insights 会直接获取此值，但这种情况通常不会发生。Cloud Insights 通常会根据各个卷的统计信息执行 IOPS 加权计算，而不是采用这种计算方法的阵列。
* 吞吐量—阵列面向主机的总吞吐量。理想情况下，如果阵列不可用， Cloud Insights 将对卷的吞吐量进行求和以得出此值
* 管理—可能包含设备管理界面的超链接。由 Cloud Insights 数据源在清单报告中以编程方式创建




=== 存储池

* 存储—此池所在的存储阵列。必填
* type —从枚举的可能性列表中获取的描述性值。最常见的配置为 " 精简配置 " 或 "RAID 组 "
* 节点—如果此存储阵列的架构使池属于特定存储节点，则其名称将在此处显示为指向其自身登录页面的超链接
* 使用 Flash Pool —是 / 否值
* 冗余— RAID 级别或保护方案。E 系列报告 DDP 池的 "RAID 7"
* 容量—此处的值为逻辑已用容量，可用容量和逻辑总容量以及这些容量中使用的百分比。这些值都包括 E 系列的 " 保留 " 容量，因此数字和百分比均高于 E 系列自己的用户界面显示的值
* 过量使用的容量—如果您通过效率技术分配的总卷或内部卷容量大于存储池的逻辑容量，则此处的百分比值将大于 0% 。
* Snapshot —已用快照容量和总容量，前提是存储池架构将部分容量专用于专为快照划分的区域
* 利用率—一个百分比值，显示为该存储池贡献容量的任何磁盘的最高磁盘繁忙百分比。磁盘利用率不一定与阵列性能密切相关—如果没有主机驱动的工作负载，则由于磁盘重建，重复数据删除活动等，利用率可能会很高。此外，许多阵列的复制实施可能会提高磁盘利用率，但不会显示为卷工作负载。
* IOPS —为该存储池贡献容量的所有磁盘的 IOPS 之和。如果磁盘 IOPS 在给定平台上不可用，则此值将来自此存储池中所有卷的卷 IOPS 之和
* 吞吐量—为该存储池贡献容量的所有磁盘的总吞吐量。如果给定平台上没有可用的磁盘吞吐量，则此值将来自此存储池中所有卷的卷吞吐量总和




=== 存储节点

* 存储—此节点所属的存储阵列。必填
* HA 配对节点—在某个节点将故障转移到一个且只有另一个节点的平台上，通常会显示在此处
* 状态—节点的运行状况。仅当阵列运行状况良好，足以供数据源进行资源清点时才可用
* model —节点的型号名称
* version —设备的版本名称。
* Serial Number —节点序列号
* 内存—如果可用，则为基础 2 内存
* 利用率—通常为 CPU 利用率数值，对于 NetApp ONTAP ，则为控制器压力指数。目前， NetApp E 系列不支持利用率
* IOPS —表示此控制器上主机驱动的 IOPS 的数字。理想情况下，如果阵列不可用，则它直接来自阵列，它将通过将专用于此节点的卷的所有 IOPS 相加来计算。
* 延迟—表示此控制器上的典型主机延迟或响应时间的数字。理想情况下，如果阵列不可用，则可以直接从该阵列中获取，方法是从专用于此节点的卷执行 IOPS 加权计算。
* 吞吐量—表示此控制器上主机驱动的吞吐量的数字。理想情况下，如果阵列不可用，则它直接来自阵列，计算方法是将专用于此节点的卷的所有吞吐量相加。
* 处理器— CPU 计数




== 要求

* 阵列上每个控制器的 IP 地址
* 端口要求 2463




== Configuration

[cols="2*"]
|===
| 字段 | Description 


| 阵列 SANtricity 控制器 IP 的逗号分隔列表 | 阵列控制器的 IP 地址和 / 或完全限定域名 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | Description 


| 清单轮询间隔（分钟） | 默认值为 30 分钟 


| 性能轮询间隔最长为 3600 秒 | 默认值为 300 秒 
|===


== 故障排除

可以从中找到此数据收集器上的追加信息 link:concept_requesting_support.html["支持"] 页面或中的 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["数据收集器支持列表"]。
