---
sidebar: sidebar 
permalink: task_dc_emc_xio.html 
keywords: data collector, XtremeIO, EMC 
summary: 配置 XtremeIO 数据收集器。 
---
= Dell EMC XtremeIO 数据收集器
:allow-uri-read: 


[role="lead"]
EMC XtremIO 数据收集器从 EMC XtremIO 存储系统采集清单和性能数据。



== 要求

要配置 EMC XtremIO （ HTTP ）数据收集器，您必须具有：

* XtremIO 管理服务器（ XMS ）主机地址
* 具有管理员权限的帐户
* 访问端口 443 （ HTTPS ）




== 术语

Cloud Insights 从 EMC XtremIO 数据收集器采集以下清单信息。对于 Cloud Insights 收购的每种资产类型，均显示了此资产最常用的术语。查看此数据源或对其进行故障排除时，请记住以下术语：

[cols="2*"]
|===
| 供应商 / 型号术语 | Cloud Insights 术语 


| 磁盘（ SSD ） | Disk 


| 集群 | 存储 


| 控制器 | 存储节点 


| Volume | Volume 


| LUN 映射 | 卷映射 


| 目标 FC 启动程序 | 卷掩码 
|===
注意：这些只是常见的术语映射，可能并不代表此数据源的所有情形。



== 要求

* XtremIO 管理服务器（ XMS ）主机 IP 地址
* XtremIO 的管理员用户名和密码




== Configuration

[cols="2*"]
|===
| 字段 | Description 


| XMS 主机 | XtremIO 管理服务器的 IP 地址或完全限定域名 


| 用户名 | XtremIO 管理服务器的用户名 


| Password | XtremIO 管理服务器的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | Description 


| TCP 端口 | 用于连接到 XTremIO 管理服务器的 TCP 端口。默认值为 443. 。 


| 清单轮询间隔（分钟） | 两次清单轮询的间隔。默认值为 60 分钟。 


| 性能轮询间隔（秒） | 性能轮询之间的时间间隔。默认值为 300 秒。 
|===


== 故障排除

可从中找到此数据收集器上的追加信息 link:concept_requesting_support.html["支持"] 页面或中的 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["数据收集器支持列表"]。
