---
sidebar: sidebar 
permalink: task_view_configured_data_collectors.html 
keywords: acquisition, AU, data collector, collector, bulk edit, postpone polling, resume polling 
summary: 摘要。 
---
= 管理已配置的数据收集器
:allow-uri-read: 


[role="lead"]
通过 "Installed Data Collectors" 页面，您可以访问为 Cloud Insights 配置的数据收集器。您可以使用此页面修改现有数据收集器。

.步骤
. 在 Cloud Insights 菜单中，单击 * 管理 > 数据收集器 *
+
此时将显示 Available Data Collector 屏幕。

. 单击 * 已安装的数据收集器 *
+
此时将显示所有已安装的数据收集器的列表。此列表提供了收集器名称，状态，收集器正在访问的 IP 地址以及上次从 A 设备采集数据的时间。可在此屏幕上执行的操作包括：

+
** 控制轮询
** 更改数据收集器凭据
** 克隆数据收集器






== 控制 Data Collector 轮询

对数据收集器进行更改后，您可能希望它立即轮询以检查所做的更改，或者在处理问题时，您可能希望将数据收集器上的数据收集延迟一，三或五天。

.步骤
. 在 Cloud Insights 菜单中，单击 * 管理 > 数据收集器 *
. 单击 * 已安装的数据收集器 *
. 选中要更改的 Data Collector 左侧的复选框
. 单击 * 批量操作 * 并选择要执行的轮询操作。
+
可以在多个数据收集器上同时执行批量操作。选择数据收集器，然后从 * 批量操作 * 菜单中选择要执行的操作。





== 编辑数据收集器信息

您可以编辑现有数据收集器设置信息。

.要编辑单个数据收集器，请执行以下操作：
. 在 Cloud Insights 菜单中，单击 * 管理 > 数据收集器 * 以打开已安装的数据收集器列表。
. 在要修改的数据收集器右侧的选项菜单中，单击 * 编辑 * 。
+
此时将打开编辑收集器对话框。

. 输入所做的更改并单击 * 测试配置 * 以测试新配置，或者单击 * 保存 * 以保存配置。


您还可以编辑多个数据收集器：

. 选中要更改的每个数据收集器左侧的复选框。
. 单击 * 批量操作 * 按钮并选择 * 编辑 * 以打开编辑数据收集器对话框。
. 按上述方式修改字段。
+

NOTE: 选定的数据收集器必须是相同的供应商和型号，并且位于同一个采集单元上。

+
编辑多个数据收集器时， " 数据收集器名称 " 字段显示 " 混合 " ，无法编辑。用户名和密码等其他字段显示为 " 混合 " ，可以进行编辑。在选定数据收集器中共享相同值的字段将显示当前值，并且可以进行编辑。

+
编辑多个数据收集器时， * 测试配置 * 按钮不可用。





== 克隆数据收集器

使用克隆工具，您可以快速添加与其他数据源具有相同凭据和属性的数据源。通过克隆，您可以轻松配置同一设备类型的多个实例。

.步骤
. 在 Cloud Insights 菜单中，单击 * 管理 > 数据收集器 * 。
. 单击 * 已安装的数据收集器 * 。
. 单击要复制的数据收集器左侧的复选框。
. 在选定数据收集器右侧的选项菜单中，单击 * 克隆 * 。
+
此时将显示克隆数据收集器对话框。

. 在必填字段中输入新信息。
. 单击 * 保存 * 。


克隆操作会复制所有其他属性和设置以创建新的数据收集器。



== 对数据收集器执行批量操作

您可以同时编辑多个数据收集器的某些信息。通过此功能，您可以对多个数据收集器启动轮询，延迟轮询以及恢复轮询。此外，您还可以删除多个数据收集器。

.步骤
. 在 Cloud Insights 菜单中，单击 * 管理 > 数据收集器 *
. 单击 * 已安装的数据收集器 *
. 单击要修改的数据收集器左侧的复选框。
. 在右侧的选项菜单中，单击要执行的选项。


您选择的操作将在数据收集器上执行。如果选择删除数据收集器，则会显示一个对话框，要求您遵从此操作。
