---
sidebar: sidebar 
permalink: task-planning-your-config-gcp.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, use profile, thin provisioning, deduplication, compression, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size, supported machine types, supported virtual machines, supported vms, supported instances 
summary: 部署 Cloud Volumes ONTAP 时、您可以选择符合工作负载要求的预配置系统、也可以创建自己的配置。如果您选择自己的配置、则应了解可用的选项。 
---
= 在Google Cloud中规划Cloud Volumes ONTAP 配置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在 Google Cloud 中部署 Cloud Volumes ONTAP 时，您可以选择符合工作负载要求的预配置系统，也可以创建自己的配置。如果您选择自己的配置、则应了解可用的选项。



== 选择Cloud Volumes ONTAP 许可证

Cloud Volumes ONTAP 提供了多种许可选项。每个选项都允许您选择一种满足您需求的消费模式。

* link:concept-licensing.html["了解 Cloud Volumes ONTAP 的许可选项"]
* link:task-set-up-licensing-google.html["了解如何设置许可"]




== 选择支持的区域

大多数 Google Cloud 地区均支持 Cloud Volumes ONTAP 。 https://cloud.netapp.com/cloud-volumes-global-regions["查看支持的区域的完整列表"^]。



== 选择支持的计算机类型

Cloud Volumes ONTAP 支持多种计算机类型，具体取决于您选择的许可证类型。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["GCP中支持的Cloud Volumes ONTAP配置"^]



== 了解存储限制

Cloud Volumes ONTAP 系统的原始容量限制与许可证相关。附加限制会影响聚合和卷的大小。在规划配置时，您应该了解这些限制。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-gcp.html["GCP中Cloud Volumes ONTAP的存储限制"^]



== 在GCP中估算系统规模

对 Cloud Volumes ONTAP 系统进行规模估算有助于满足性能和容量要求。在选择计算机类型，磁盘类型和磁盘大小时，您应注意几个要点：

计算机类型:: 在中查看支持的计算机类型 http://docs.netapp.com/cloud-volumes-ontap/us-en/index.html["《 Cloud Volumes ONTAP 发行说明》"^] 然后查看 Google 提供的有关每个受支持计算机类型的详细信息。将工作负载要求与此计算机类型的 vCPU 和内存数量相匹配。请注意，每个 CPU 核心都会提高网络连接性能。
+
--
有关更多详细信息，请参见以下内容：

* https://cloud.google.com/compute/docs/machine-types#n1_machine_types["Google Cloud 文档： N1 标准计算机类型"^]
* https://cloud.google.com/docs/compare/data-centers/networking#performance["Google Cloud 文档：性能"^]


--
GCP磁盘类型:: 在为 Cloud Volumes ONTAP 创建卷时，您需要选择 Cloud Volumes ONTAP 用于磁盘的底层云存储。磁盘类型可以是以下任一项：
+
--
* _Zonal SSD Persistent disks_： SSD 永久性磁盘最适合需要高随机 IOPS 速率的工作负载。
* _Zonal Balanced_Persistent disks_： 这些 SSD 通过提供更低的每 GB IOPS 来平衡性能和成本。
* _Zonal Standard Persistent disks_： 标准持久性磁盘经济实惠，可以处理顺序读 / 写操作。
+
有关详细信息，请参见 https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud 文档：区域持久性磁盘（标准和 SSD ）"^]。



--
GCP磁盘大小:: 部署 Cloud Volumes ONTAP 系统时，您需要选择初始磁盘大小。之后、您可以让BlueXP为您管理系统的容量、但如果您要自行构建聚合、请注意以下事项：
+
--
* 聚合中的所有磁盘大小必须相同。
* 确定所需空间，同时考虑性能。
* 永久性磁盘的性能会随磁盘大小和系统可用的 vCPU 数量自动扩展。
+
有关更多详细信息，请参见以下内容：

+
** https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud 文档：区域持久性磁盘（标准和 SSD ）"^]
** https://cloud.google.com/compute/docs/disks/performance["Google Cloud 文档：优化持久磁盘和本地 SSD 性能"^]




--




== 查看默认系统磁盘

除了用户数据存储之外、BlueXP还为Cloud Volumes ONTAP 系统数据(启动数据、根数据、核心数据和NVRAM)购买云存储。出于规划目的，在部署 Cloud Volumes ONTAP 之前查看这些详细信息可能会有所帮助。

* link:reference-default-configs.html#google-cloud-single-node["在 Google Cloud 中查看 Cloud Volumes ONTAP 系统数据的默认磁盘"]。
* https://cloud.google.com/compute/quotas["Google Cloud 文档：资源配额"^]
+
Google 云计算引擎对资源使用量实施配额，因此在部署 Cloud Volumes ONTAP 之前，您应确保未达到限制。




TIP: 此连接器还需要一个系统磁盘。 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-connector-default-config.html["查看有关连接器默认配置的详细信息"^]。



== 收集网络信息

在 GCP 中部署 Cloud Volumes ONTAP 时，需要指定有关虚拟网络的详细信息。您可以使用工作表从管理员收集信息。

* 单节点系统的网络信息 *

[cols="30,70"]
|===
| GCP信息 | 您的价值 


| Region |  


| 分区 |  


| VPC 网络 |  


| Subnet |  


| 防火墙策略（如果使用自己的策略） |  
|===
* 多个分区中 HA 对的网络信息 *

[cols="30,70"]
|===
| GCP信息 | 您的价值 


| Region |  


| 节点 1 的分区 |  


| 节点2的分区 |  


| 调解器的分区 |  


| vPC-0 和子网 |  


| vPC-1 和子网 |  


| vPC-2 和子网 |  


| vPC-3 和子网 |  


| 防火墙策略（如果使用自己的策略） |  
|===
* 单个分区中 HA 对的网络信息 *

[cols="30,70"]
|===
| GCP信息 | 您的价值 


| Region |  


| 分区 |  


| vPC-0 和子网 |  


| vPC-1 和子网 |  


| vPC-2 和子网 |  


| vPC-3 和子网 |  


| 防火墙策略（如果使用自己的策略） |  
|===


== 选择写入速度

您可以通过BlueXP为Cloud Volumes ONTAP 选择写入速度设置、但Google Cloud中的高可用性(HA)对除外。在选择写入速度之前、您应该了解正常和高设置之间的差异、以及使用高速写入速度时的风险和建议。 link:concept-write-speed.html["了解有关写入速度的更多信息。"]。



== 选择卷使用情况配置文件

ONTAP 包含多种存储效率功能、可以减少您所需的存储总量。在BlueXP中创建卷时、您可以选择启用这些功能的配置文件或禁用这些功能的配置文件。您应该了解有关这些功能的更多信息、以帮助您确定要使用的配置文件。

NetApp 存储效率功能具有以下优势：

精简配置:: 为主机或用户提供的逻辑存储比实际在物理存储池中提供的存储多。在写入数据时，存储空间将动态分配给每个卷而不是预先分配存储空间。
重复数据删除:: 通过定位相同的数据块并将其替换为单个共享块的引用来提高效率。此技术通过消除驻留在同一卷中的冗余数据块来降低存储容量需求。
压缩:: 通过在主存储、二级存储和归档存储上的卷中压缩数据来减少存储数据所需的物理容量。

