---
sidebar: sidebar 
permalink: task_dc_ibm_powervm.html 
keywords: IBM, powerVM, 
summary: 配置 IBM PowerVM 数据收集器。 
---
= 配置 IBM PowerVM 数据收集器


[role="lead"]
IBM PowerVM （ SSH ）数据收集器用于收集有关在由硬件管理控制台（ HMC ）管理的 IBM POWER 硬件实例上运行的虚拟分区的信息。



== 术语

Cloud Insights 从 IBM POWER 硬件实例上运行的虚拟分区获取清单信息。对于所采集的每种资产类型，都会显示该资产最常用的术语。查看此数据收集器或对其进行故障排除时，请记住以下术语：

[cols="2*"]
|===
| 供应商 / 型号术语 | Cloud Insights 术语 


| hdisk | 虚拟磁盘 


| 受管系统 | 主机 


| LPAR ， VIO 服务器 | 虚拟机 


| 卷组 | 数据存储 


| 物理卷 | LUN 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情形。



== 要求

要配置和使用此数据收集器，必须满足以下要求：

* 硬件管理控制台（ HMC ）的 IP 地址
* 用于通过 SSH 访问硬件管理控制台（ HMC ）的用户名和密码
* 端口要求 SSH-22
* 查看所有管理系统和逻辑分区安全域的权限
+
用户还必须对 HMC 配置拥有查看权限，并能够为 HMC 控制台安全分组收集 VPD 信息。在逻辑分区安全分组下，还必须允许用户访问虚拟 IO 服务器命令。最好从操作员角色开始，然后删除所有角色。HMC 上的只读用户无权在 AIX 主机上运行代理命令。

* IBM 最佳实践是，让两个或更多 HMCS 监控设备。请注意，这可能是发生原因 OnCommand Insight 报告重复的设备，因此强烈建议将冗余设备添加到此数据收集器的高级配置中的 " 排除设备 " 列表中。




== Configuration

[cols="2*"]
|===
| 字段 | Description 


| 硬件管理控制台（ HMC ） IP 地址 | PowerVM 硬件管理控制台的 IP 地址或完全限定域名 


| HMC 用户 | 硬件管理控制台的用户名 


| Password | 硬件管理控制台使用的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | Description 


| 清单轮询间隔（分钟） | 两次清单轮询的间隔。默认值为 20 分钟。 


| SSH 端口 | 用于通过 SSH 连接到 PowerVM 的端口 


| Password | 硬件管理控制台使用的密码 


| 重试次数 | 清单重试尝试次数 


| 排除设备 | 要排除的设备 ID 或显示名称的逗号分隔列表 
|===


== 故障排除

可从中找到此数据收集器上的追加信息 link:concept_requesting_support.html["支持"] 页面或中的 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["数据收集器支持列表"]。
