---
sidebar: sidebar 
permalink: task_business_entity_annotations.html 
keywords: annotations, business entity 
summary: 业务实体标注可用于监控和报告业务层次结构中的资产 
---
= 业务实体标注


[role="lead"]
使用 * 业务实体 * 标注类型为您的企业环境创建和管理业务实体。



== 创建业务实体

要创建业务实体，请执行以下操作：

. 单击 * 管理 > 标注 * ，然后单击 _Business Entity_ 链接。
+
此时将显示当前定义的业务实体的列表。

. 单击 * + Business Entity* 。
. 为 * 租户 * ， * 业务线 * ， * 业务单位 * 和 * 项目 * 字段输入值。
+
如果任何字段不适用于您的业务实体，您可以将其留空。

. 如果您先前已为某个字段输入值，则可以从下拉列表中选择该值。您无需再次键入。



NOTE: 选定值必须构成唯一的 Total Business 实体。例如，如果您已有一个业务实体的值为 _A/B/C/ D_ ，则不能按该顺序创建具有这些值的其他业务实体。但是，您可以使用这些值按不同顺序创建业务实体。



== 将业务实体应用于对象

将业务实体应用于一个或多个对象的最简单方法是通过查询。

. 单击 * 查询 > +New Query* 并选择所需的对象类型。您可以应用筛选器以进一步缩小结果范围。
. 单击此复选框以选择要应用业务实体的对象。
. 单击 * 批量操作 * 并选择 * 添加标注 * 。
. 选择 _Business Entity_ 标注，然后从列表中选择所需的业务实体值。
. 单击 * 保存 * 将业务实体应用于对象。


您还可以通过导航到某个业务实体的资产登录页面并单击用户数据部分中的 * + 标注来将此业务实体应用于单个对象。

您也可以配置 link:task_create_annotation_rules.html["标注规则"] 将业务实体应用于对象。


NOTE: 一个对象只能有一个关联的业务实体。



== 从对象中删除业务实体

要从一个或多个对象中删除业务实体，请查询并选择该对象，单击 * 批量操作 * 并选择 _Remove Annotation_.选择 Business Entity 标注，然后单击 * 删除 * 。
