---
sidebar: sidebar 
permalink: task_dc_emc_vnx_unified.html 
keywords: data collector, VNX, EMC, Dell 
summary: 配置 VNX 数据收集器。 
---
= 配置 Dell EMC VNX 统一数据收集器


[role="lead"]
在配置方面， Dell EMC VNX Unified （ SSH ）数据收集器需要控制站的 IP 地址以及只读用户名和密码。



== 术语

Cloud Insights 从此数据收集器获取以下清单信息。对于 Cloud Insights 收购的每种资产类型，均显示了此资产最常用的术语。查看此数据收集器或对其进行故障排除时，请记住以下术语：

[cols="2*"]
|===
| 供应商 / 型号术语 | Cloud Insights 术语 


| Disk | Disk 


| 磁盘文件夹 | 磁盘组 


| 文件系统 | 内部卷 


| 存储 | 存储 


| 存储处理器 | 存储节点 


| 存储池， RAID 组 | 存储池 


| LUN | Volume 


| 数据移动 | 控制器 


| 数据移动器上挂载的文件系统 | 文件共享 


| CIFS 和 NFS 导出 | 共享 


| 磁盘卷 | 后端 LUN 
|===


== 要求

要配置 VNX （ SSH ）数据收集器，需要满足以下要求：

* Celerra Control Station 的 VNX IP 地址和凭据。
* 只读用户名和密码。
* 数据收集器可以使用 DART OS NAS 机头对后端阵列运行 NaviCLI/NaviSecCLI 命令




== Configuration

[cols="2*"]
|===
| 字段 | Description 


| VNX IP 地址 | VNX 控制站的 IP 地址或完全限定域名 


| 用户名 | VNX 控制站的用户名 


| Password | VNX 控制站的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | Description 


| 清单轮询间隔（分钟） | 两次清单轮询的间隔。默认值为 40 分钟。 


| 性能轮询间隔（秒）。 | 性能轮询之间的时间间隔。默认值为 300 秒。 
|===


== 故障排除

可从中找到此数据收集器上的追加信息 link:concept_requesting_support.html["支持"] 页面或中的 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["数据收集器支持列表"]。
