---
sidebar: sidebar 
permalink: task_isolate_root_volume.html 
summary: 在查询高 I/O 密度时，您希望排除根卷。 
keywords: NetApp, root volume, high I/O, 
---
= 确保 IO 密度报告仅描述内部数据卷
:allow-uri-read: 


[role="lead"]
NetApp 根卷包含用于管理存储系统的目录和配置文件。在查询高 I/O 密度时，您希望排除这些根卷。

在监控您的环境时，更重要的是确定哪些内部数据卷产生了高 I/O 密度数字。为了准确地识别数据卷，您需要将 NetApp 内部卷与用于监控 I/O 密度的查询隔离开来。

本指南介绍如何轻松识别 NetApp 根聚合，将其与内部卷查询结果隔离以及创建规则，以便在将任何新的 NetApp 根聚合添加到系统中时将其排除。以下 Insight 功能用于确保 I/O 密度报告源自内部数据卷：

* 系统将创建一个查询来标识 Insight 监控的所有 NetApp 根聚合。
* 系统会为每个 NetApp 根聚合分配一个标注。
* 此时将创建一个标注规则，以便将标注应用于新的 NetApp 根聚合。


本指南中的步骤也可应用于其他供应商的存储系统。您需要确定包含用于管理存储系统的目录和配置文件的卷，并使用类似的步骤排除这些卷。



== 创建查询以确定环境中的 NetApp 根聚合

查询可根据用户选择的条件精细地进行搜索。使用查询可以搜索环境中包含 NetApp 根聚合的内部卷。

. 步骤
. 创建查询以确定环境中的 NetApp 根聚合：单击 * 查询 > 新建查询 > 选择资源类型 * （？）
. 单击 * 存储池 *
. 输入根聚合的名称
+
此示例对名称使用 "aggr0" 。创建聚合时，只需满足以下名称要求： .它必须以字母或下划线（ _ ）开头。...它只能包含字母，数字和下划线。...字符数不能超过 250 个。在大多数情况下，聚合的名称为 aggr0 ， aggr_0 或类似的内容。要确定环境中的所有 NetApp 根聚合，可能需要一个迭代过程。

. 单击 * 保存 * 并输入新查询的名称。
+
如前所述，此过程可能是一个迭代过程，需要多次查询才能确定所有 NetApp 根聚合。





== 为查询返回的根卷创建标注

标注是您分配给资产的专用注释，可用于按资产标注筛选资产。您创建的标注将用于标识环境中的 NetApp 根聚合，并确保它们不包含在特定报告中。

.开始之前
您必须已确定要从 " 高 I/O 密度 " 报告中排除的所有根聚合。

.步骤
. 在 Cloud Insights 菜单中，单击 * 管理 > 标注 *
. 单击 * 添加 * 。
+
.. 输入标注的名称： * RootAggr*
.. 输入标注的问题描述： * 从 " 高 I/O 密度 " 报告中删除根聚合 *
.. 输入标注类型： * 布尔值 *


. 单击 * 保存 * 。




== 创建标注规则以自动从 I/O 密度报告中排除特定聚合

除了手动将标注应用于单个资产之外，您还可以使用标注规则自动将标注应用于多个资产。标注规则基于您创建的查询，在系统上运行时，它们会将新资产添加到现有资产集。如果从报告中排除这些资产集，则新资产也会自动排除。

.开始之前
您必须已创建并保存一个查询，用于标识您在环境中标识的 NetApp 根聚合。。步骤在 Cloud Insights 工具栏中，单击 * 管理 > 标注规则 * 。单击 * 添加 * 。

+ 此时将显示添加规则对话框： .在名称框中，输入用于描述规则的唯一名称： *"RootAggrExcluse"* .单击 Query 并选择 Insight 应用标注规则时应使用的查询： *"Aggregate0"* 。单击标注并选择： *" 根 AGG 排除 "* .单击 * 值 * 并输入 * 正确 *
