---
sidebar: sidebar 
permalink: task-aws-key-management.html 
keywords: aws, amazon, encryption, NVE, NetApp volume encryption, KMIP, kms, key manager service 
summary: 利用AWS的密钥管理服务提供第三方密钥管理服务。 
---
= 使用AWS密钥管理服务管理密钥
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 link:https://docs.aws.amazon.com/kms/latest/developerguide/overview.html["AWS的密钥管理服务(KMS)"^] 在部署了Google Cloud Platform的应用程序中保护ONTAP 加密密钥。

可以使用命令行界面或ONTAP REST API启用AWS KMS的密钥管理。

使用KMS时、请注意、默认情况下、数据SVM的LIF用于与云密钥管理端点进行通信。节点管理网络用于与AWS的身份验证服务进行通信。如果集群网络配置不正确，集群将无法正确利用密钥管理服务。

.开始之前
* Cloud Volumes ONTAP必须运行9.12.0或更高版本
* 您必须已安装卷加密(VE)许可证和
* 您必须已安装多租户加密密钥管理(MTEKM)许可证。
* 您必须是集群管理员或SVM管理员
* 您必须拥有有效的AWS订阅



NOTE: 您只能为数据SVM配置密钥。



== Configuration

.AWS
. 您必须创建 link:https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#grant["授予"^] 用于管理加密的IAM角色要使用的AWS KMS密钥。IAM角色必须包含一个允许执行以下操作的策略：
+
** `DescribeKey`
** `Encrypt`
** `Decrypt`
要创建授予、请参见 link:https://docs.aws.amazon.com/kms/latest/developerguide/create-grant-overview.html["AWS文档"^]。


. link:https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html["将策略添加到相应的IAM角色。"^] 此策略应支持 `DescribeKey`， `Encrypt`，和 `Decrypt` 操作。


.Cloud Volumes ONTAP
. 切换到Cloud Volumes ONTAP环境。
. 切换到高级权限级别：
`set -privilege advanced`
. 启用AWS密钥管理器：
`security key-manager external aws enable -vserver _data_svm_name_ -region _AWS_region_ -key-id _key_ID_ -encryption-context _encryption_context_`
. 出现提示时、输入机密密钥。
. 确认已正确配置AWS KMS：
`security key-manager external aws show -vserver _svm_name_`

