---
sidebar: sidebar 
permalink: task_defining_annotations.html 
keywords: annotations, monitor, notes, tags 
summary: 使用标注跟踪数据。 
---
= 定义标注


[role="lead"]
在自定义 Cloud Insights 以根据企业要求跟踪数据时，您可以定义称为标注的专用注释并将其分配给资产。

您可以使用资产生命周期结束，数据中心，构建位置，存储层或卷服务级别等信息为资产分配标注。

使用标注帮助监控您的环境包括以下高级任务：

* 为所有标注类型创建或编辑定义。
* 显示资产页面并将每个资产与一个或多个标注相关联。
+
例如，如果某个资产正在租赁，并且租约在两个月内到期，则您可能需要对该资产应用寿命终结标注。这有助于防止他人长时间使用该资产。

* 创建规则以自动将标注应用于同一类型的多个资产。
* 按标注筛选资产。




== 默认标注类型

Cloud Insights 提供了一些默认标注类型。这些标注可用于筛选或分组数据。

您可以将资产与以下默认标注类型关联：

* 资产生命周期，例如，生日，日出或生命周期结束
* 有关设备的位置信息，例如数据中心，建筑物或楼层
* 按质量（层），已连接设备（交换机级别）或服务级别等对资产进行分类
* 状态，例如热（高利用率）


下表列出了 Cloud Insights 提供的标注类型。

[cols="30,53, 16"]
|===


| 标注类型 | Description | Type 


| 别名 | 资源的用户友好名称 | 文本 


| 计算资源组 | 主机和 VM 文件系统数据收集器使用的组分配 | 列表 


| 数据中心 | 物理位置 | 列表 


| 热 | 设备经常频繁使用或处于容量阈值 | 布尔值 


| 注意 | 与资源关联的注释 | 测试 


| 服务级别 | 一组可分配给资源的受支持服务级别。提供内部卷， qtree 和卷的有序选项列表。编辑服务级别以设置不同级别的性能策略。 | 列表 


| 《日出》 | 设置的阈值，超过此阈值后，无法为该设备进行新分配。适用于计划内迁移和其他待定网络更改。 | Date 


| 交换机级别 | 用于设置交换机类别的预定义选项。通常，这些指定值在设备生命周期内保持不变，但您可以对其进行编辑。仅适用于交换机。 | 列表 


| 层 | 可用于定义环境中的不同服务级别。层可以定义级别的类型，例如所需的速度（例如金牌或银牌）。此功能仅适用于内部卷， qtree ，存储阵列，存储池和卷。 | 列表 


| 违规严重性 | 在重要性从高到低的层次结构中对违规（例如，缺少主机端口或缺少冗余）进行排名（例如，重大）。 | 列表 
|===

NOTE: 别名，数据中心，热，服务级别， Sunset ， 交换机级别，层和违规严重性是系统级别的标注，您不能删除或重命名这些标注；您只能更改其分配的值。



== 创建自定义标注

通过标注，您可以将符合业务需求的自定义业务特定数据添加到资产中。虽然 Cloud Insights 提供了一组默认标注，但您可能会发现您希望以其他方式查看数据。自定义标注中的数据可补充已收集的设备数据，例如存储制造商，卷数量和性能统计信息。Cloud Insights 不会发现您使用标注添加的数据。

.步骤
. 在 Cloud Insights 菜单中，单击 * 管理 > 标注 * 。
+
" 标注 " 页面将显示标注列表。

. 单击 * + 添加 *
. 输入标注的 * 名称 * 和 * 问题描述 * 。
+
您最多可以在这些字段中输入 255 个字符。

. 单击 * 类型 * ，然后选择以下选项之一，以表示此标注中允许的数据类型：


.标注类型
布尔值:: 创建一个下拉列表，其中包含 yes 和 no 选项例如， " 直连 " 标注为布尔标注。
Date:: 此操作将创建一个包含日期的字段。例如，如果标注将是日期，请选择此项。
列表::
+
--
* 固定下拉列表
+
当其他用户在设备上分配此标注类型时，他们无法向列表中添加更多值。

* 下拉灵活列表
+
如果在创建此列表时选择 Add new values on the fly 选项，则当其他人在设备上分配此标注类型时，他们可以向列表中添加更多值。



--
数字:: 创建一个字段，分配标注的用户可以在此字段中输入数字。例如，如果标注类型为 " 楼层 " ，则用户可以选择 " 数字 " 值类型并输入楼层编号。
文本:: 创建一个允许自由格式文本的字段。例如，您可以输入 " 语言 " 作为标注类型，选择 " 文本 " 作为值类型，然后输入语言作为值。



NOTE: 设置类型并保存更改后，您将无法更改标注的类型。如果需要更改类型，则必须删除标注并创建一个新标注。

. 如果选择 List 作为标注类型，请执行以下操作：
+
.. 如果您希望在资产页面上为标注添加更多值，请选择 * 即时添加新值 * ，这样可以创建灵活列表。
+
例如，假设您位于资产页面上，并且资产的 City 标注值为 Detroit ， TampA 和 Boston 。如果您选择了 * 实时添加新值 * 选项，则可以直接在资产页面上将其他值添加到 City ，例如旧金山和芝加哥，而无需转到标注页面进行添加。如果不选择此选项，则在应用标注时无法添加新标注值；这将创建一个固定列表。

.. 在 * 值 * 和 * 问题描述 * 字段中输入一个值和问题描述。
.. 单击 *+Add+* 以添加其他值。
.. 单击 " 垃圾桶 " 图标可删除某个值。


. 单击 * 保存 * 。
+
您的标注将显示在标注页面的列表中。



在用户界面中，此标注可立即使用。
