---
sidebar: sidebar 
permalink: task_create_annotation.html 
keywords: annotations, annotation rules, manual annotations, 
summary: 如何创建标注。 
---
= 使用标注
:allow-uri-read: 


[role="lead"]
您可以创建标注并将其分配给所监控的资产。标注是指提供资产相关信息的注释，例如物理位置，使用寿命终结，存储层或卷服务级别。



== 定义标注

通过标注，您可以将符合业务需求的自定义业务特定数据添加到资产中。虽然 Cloud Insights 提供了一组默认标注，例如资产生命周期（生日或生命周期结束），建筑物或数据中心位置以及层，但您可能会发现您希望以其他方式查看数据。

自定义标注中的数据可补充已收集的设备数据，例如交换机制造商，端口数量和性能统计信息。Cloud Insights 不会发现您使用标注添加的数据。

.开始之前
* 列出环境数据必须关联的任何行业术语。
* 列出环境数据必须关联的企业术语。
* 确定您可以使用的任何默认标注类型。
* 确定需要创建哪些自定义标注。您需要先创建标注，然后才能将其分配给资产。


按照以下步骤创建标注。

.步骤
. 在 Cloud Insights 菜单中，单击 * 管理 > 标注 *
. 单击 * + Annotation * 以创建新标注。
. 为新标注输入名称，问题描述和类型。
+
例如，输入以下内容创建一个文本标注，用于定义资产在 Data Center 4 中的物理位置：

+
** 输入标注的名称，例如 " 位置 "
** 输入标注所描述的问题描述，例如 " 物理位置是数据中心 4"
** 输入标注的 " 类型 " ，例如 " 文本 " 。






== 手动为资产分配标注

为资产分配标注有助于您按照与业务相关的方式对资产进行排序，分组和报告。尽管您可以使用标注规则自动为特定类型的资产分配标注，但您可以使用资产页面为单个资产分配标注。

.开始之前
* 您必须已创建要分配的标注。


.步骤
. 登录到 Cloud Insights 环境。
. 找到要应用标注的资产。
+
** 您可以通过查询，从 dashoard 小工具中选择或搜索来查找资产。找到所需资产后，单击相应链接以打开该资产的登录页面。


. 在资产页面的 User Data 部分中，单击 * + Annotation * 。
. 此时将显示添加标注对话框。
. 从列表中选择一个标注。
. 单击 Value ，然后根据您选择的标注类型执行以下操作之一：
+
** 如果标注类型为 list ， date 或 boolean ，请从列表中选择一个值。
** 如果标注类型为文本，请键入一个值。


. 单击 * 保存 * 。


如果要在分配后更改标注的值，请单击标注字段并选择其他值。如果标注的列表类型选择了 _Add new values on the fly_ 选项，则除了选择现有值之外，您还可以键入新值。



== 使用标注规则分配标注

要根据定义的条件自动为资产分配标注，请配置标注规则。Cloud Insights 会根据这些规则为资产分配标注。Cloud Insights 还提供了两个默认标注规则，您可以根据需要修改这些规则，如果不想使用这些规则，则可以将其删除。



=== 正在创建标注规则

除了手动将标注应用于单个资产之外，您还可以使用标注规则自动将标注应用于多个资产。在 Insight 评估标注规则时，在单个资产页面上手动设置的标注优先于基于规则的标注。

.开始之前
您必须已为标注规则创建查询。

.关于此任务
虽然您可以在创建规则时编辑标注类型，但您应提前定义这些类型。

.步骤
. 单击 * 管理 > 标注规则 *
+
" 标注规则 " 页面将显示现有标注规则的列表。

. 单击 * + Add* 。
. 执行以下操作：
+
.. 在 * 名称 * 框中，输入用于描述规则的唯一名称。
+
此名称将显示在 "Annotation Rules" 页面中。

.. 单击 * 查询 * ，然后选择用于将标注应用于资产的查询。
.. 单击 * 标注 * 并选择要应用的标注。
.. 单击 * 值 * 并为标注选择一个值。
+
例如，如果选择 " 生日 " 作为标注，则可以为此值指定日期。

.. 单击 * 保存 * 。
.. 如果要立即运行所有规则，请单击 * 运行所有规则 * ；否则，这些规则将按计划的定期间隔运行。



