---
sidebar: sidebar 
permalink: task_dc_ibm_svc.html 
keywords: IBM, SVC,SAN 
summary: 配置 IBM SAN Volume Controller 数据收集器。 
---
= 配置 IBM SAN Volume Controller 数据收集器
:allow-uri-read: 


[role="lead"]
IBM SAN Volume Controller （ SVC ）数据收集器使用 SSH 收集清单和性能数据，从而支持运行 SVC 操作系统的各种设备。

支持的设备列表包括 SVC ， v7000 ， V5000 和 V3700 等型号。有关支持的型号和固件版本，请参见 Cloud Insights 支持列表。



== 术语

Cloud Insights 从 IBM SVC 数据收集器获取以下清单信息。对于 Cloud Insights 收购的每种资产类型，均显示了此资产最常用的术语。查看此数据收集器或对其进行故障排除时，请记住以下术语：

[cols="2*"]
|===
| 供应商 / 型号术语 | Cloud Insights 术语 


| 驱动器 | Disk 


| 集群 | 存储 


| Node | 存储节点 


| Mdisk 组 | 存储池 


| vDisk | Volume 


| Mdisk | 后端 LUN 和路径 
|===
注意：这些只是常见的术语映射，可能并不代表此数据收集器的所有情形。



=== 清单要求

* 每个 SVC 集群的 IP 地址
* 端口 22 可用
* 只读用户名和密码




=== 性能要求

* SVC 控制台，任何 SVC 集群都必须使用此控制台， SVC 发现基础包也需要此控制台。
* 只有在将性能文件从集群节点复制到配置节点时，凭据才需要管理访问级别。
* 通过 SSH 连接到 SVC 集群并运行： _svctask startstats -interval 1_ 来启用数据收集
+
注意：或者，也可以使用 SVC 管理用户界面启用数据收集。





== Configuration

[cols="2*"]
|===
| 字段 | Description 


| 集群 IP 地址 | SVC 存储的 IP 地址或完全限定域名 


| 清单用户名 | SVC 命令行界面的用户名 


| 清单密码 | SVC 命令行界面的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | Description 


| 清单轮询间隔（分钟） | 两次清单轮询的间隔。默认值为 40 分钟。 


| 性能轮询间隔（秒） | 性能轮询之间的时间间隔。默认值为 300 秒。 


| 清理转储的统计信息文件 | 选中此复选框可清除转储的统计数据文件 
|===


== 故障排除

如果此数据收集器出现问题，请尝试执行以下操作：

[cols="2*"]
|===
| 问题： | 请尝试以下操作： 


| 错误： " 无法启动此命令，因为它未在配置节点上运行。 " | 必须在配置节点上执行此命令。 
|===
如果此数据收集器出现问题，请尝试执行以下操作：

[cols="2*"]
|===
| 问题： | 请尝试以下操作： 


| 错误： " 无法启动此命令，因为它未在配置节点上运行。 " | 必须在配置节点上执行此命令。 
|===
可从中找到此数据收集器上的追加信息 link:concept_requesting_support.html["支持"] 页面或中的 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["数据收集器支持列表"]。
